### ISSUE TITLE
InputSelect not clearing message

### ISSUE THREAD

**Issue by douglassimaodev** [ryanelian/FluentValidation.Blazor#10]
Id is a Guid so "select one" has a default Guid 

<div class="col-md-6 col-sm-12">

                                            <InputSelect class="form-control" @bind-Value="Id">
                                                <option value="0000.0000.0000.0000.0000">Select One</option>
                                                @foreach (var item in items)
                                                {
                                                    <option value="@item.Id">@item.Description</option>
                                                }
                                            </InputSelect>

                                            <ValidationMessage For="@(() => Id)" />
                                        </div>

 RuleFor(x => x.PresenterIdentificationId).NotEqual(new Guid());
 RuleFor(x => x.PresenterIdentificationId).NotEmpty();

the error message only disappears when button save is clicked where  InputText removes error message after type and losing focus

**Comment by ryanelian** [comment]
IIRC Blazor does not support non-string Select Value, so this is NOT the problem of FluentValidation.Blazor library but Blazor itself.

Let me redirect your complaint to this thread: https://github.com/dotnet/aspnetcore/issues/9939

**Comment by douglassimaodev** [comment]
yah sorry about that... did a workaround 

public string IdString { get; set; }

public Guid Id
 {
            get { return Guid.TryParse(IdString , out Guid g) ? g : default; }
            set { IdString = Convert.ToString(value); }
 }

InputSelect class="form-control" @bind-Value="IdString ">
