### ISSUE TITLE
OnFieldChanged not trigger

### ISSUE THREAD

**Issue by douglassimaodev** [ryanelian/FluentValidation.Blazor#13]
I have an input where I change it using javascript, even after calling EditContext.NotifyFieldChanged, NotifyValidationStateChanged, StateHasChanged()

FluentValidator  CurrentEditContext.OnFieldChanged does not trigger..

anyidea?  the 2 way bind does work, setting the property with new value

**Comment by ryanelian** [comment]
We at Accelist have some closed source input components which are written using JS in Blazor AND working with the FluentValidator.

Unfortunately, I cannot diagnose your problem without a repro. Please send your JS component source code.
