### ISSUE TITLE
Consider using tags to version releases and use Github "releases" tab

### ISSUE THREAD

**Issue by Sebazzz** [ryanelian/FluentValidation.Blazor#18]
I just noticed this package published v2.0.0, however, it is completely unclear to me *what* has changed. Consider tagging releases in git, and publishing any release notes under the releases tab in Github.

**Comment by ryanelian** [comment]
I apologize for the sudden 2.0.0 bump last month.

This is the Release Notes published on the nuget package: https://www.nuget.org/packages/Accelist.FluentValidation.Blazor

```
Version 2.0.0 BREAKING CHANGES:
- Changed component namespace from FluentValidation.FluentValidator to Microsoft.AspNetCore.Components.Forms.FluentValidator to solve namespace-related issues when used in projects with Accelist.* namespace!
- Set ServiceScope property in component to private. (Accidentally made public!)
```

A sudden namespace change is required due to bug found in C# / Razor compiler.

**Comment by Sebazzz** [comment]
Which bug?

Met vriendelijke groet,
Sebastiaan Dammann
________________________________
Van: Ryan Elian <notifications@github.com>
Verzonden: Saturday, March 7, 2020 7:02:15 PM
Aan: ryanelian/FluentValidation.Blazor <FluentValidation.Blazor@noreply.github.com>
CC: Sebastiaan Dammann <sebastiaandammann@outlook.com>; Author <author@noreply.github.com>
Onderwerp: Re: [ryanelian/FluentValidation.Blazor] Consider using tags to version releases and use Github "releases" tab (#18)


I apologize for the sudden 2.0.0 bump last month.

This is the Release Notes published on the nuget package:

Version 2.0.0 BREAKING CHANGES:
- Changed component namespace from FluentValidation.FluentValidator to Microsoft.AspNetCore.Components.Forms.FluentValidator to solve namespace-related issues when used in projects with Accelist.* namespace!
- Set ServiceScope property in component to private. (Accidentally made public!)


A sudden namespace change is required due to bug found in C# / Razor compiler.

**Comment by ryanelian** [comment]
https://github.com/dotnet/aspnetcore/issues/18834

**Comment by ryanelian** [comment]
I believe I also put a release note in the git commit: 

https://github.com/ryanelian/FluentValidation.Blazor/commit/f297bdf913032c4634493e84baa3ef0e4ef83940

![image](https://user-images.githubusercontent.com/8892187/76150078-f8b47580-60d8-11ea-83d7-8f008db5c0f3.png)

Your suggestion however, is duly noted. I will tag 2.0.0 release note: https://github.com/ryanelian/FluentValidation.Blazor/releases/tag/2.0.0
