### ISSUE TITLE
Library is not compatible with Client-Side Blazor due to Exception with async validation 

### ISSUE THREAD

**Issue by termon** [ryanelian/FluentValidation.Blazor#26]
Hello

Have been using your FluentValidation component and note that it indicates there are issues when calling async validators. I had tried following two versions of an asynchronous rule that verifies if an email address is already registered and thus unavailable. The first causes browser to lock up, whilst second is executed and Failure added to context - though not displayed in UI. PS. 

```
public class RegisterRequestValidator : AbstractValidator<RegisterRequest>
{
      public RegisterRequestValidator(AuthService _svc)
      {            
           // this rule causes browser lockup so not used
            RuleFor(p => p.EmailAddress).MustAsync(async (email, cancellation) => {
                     bool available = await _svc.VerifyEmailAvailableAsync(email);
                     return !available;
            }).WithMessage("EmailAddress is already Registered");

            // this rule is executed but validation message is not displayed in UI
            RuleFor(p => p.EmailAddress).NotEmpty().EmailAddress()
                .Custom(async (email, context) => {
                    var available = await _svc.VerifyEmailAvailableAsync(email);                  
                    if (!available) 
                    {                      
                        context.AddFailure("EmailAddress", "Email has already been registered. Please use another.");
                    }
                }
            );              
      }    
}
```
The form
```
<EditForm Model="RegisterModel" OnValidSubmit="HandleRegistration">
        <FluentValidator />

        <div class="form-group">
                <label for="email">Email address</label>
                <InputText Id="email" class="form-control" @bind-Value="RegisterModel.EmailAddress" />
                <ValidationMessage For="@(() => RegisterModel.EmailAddress)" />
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
</EditForm>
```
Any ideas?

Thanks

Aiden

**Comment by ryanelian** [comment]
I'm not familiar with the second one, but the first one **should not** cause browsers to lock up.

This example actually does what you did, but to a fake service (invokes `Task.Delay` to emulate I/O).

https://github.com/ryanelian/FluentValidation.Blazor/blob/master/Demo/Services/EmailCheckerService.cs

https://github.com/ryanelian/FluentValidation.Blazor/blob/master/Demo/Models/FormModel2.cs#L39-L41

Our team uses `MustAsync` with Entity Framework Core async methods without issues so far...

Please send a repro to continue investigation.

**Comment by termon** [comment]
My issue is in a Blazor Wasm project - your demo is a server side blazor project. I created a blank wasm project,  and just used an async simulated service call (as per your demo) and now get a more informative error

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: An unhandled exception occurred when validating <EditForm> model type: 'Demo.Models.RegisterRequest'
Accelist.FluentValidation.Blazor.UnhandledValidationException: An unhandled exception occurred when validating <EditForm> model type: 'Demo.Models.RegisterRequest' ---> System.Threading.SynchronizationLockException: Cannot wait on monitors on this runtime.

```

Let me know if you still need a repo containing the example that causes this error

**Comment by ryanelian** [comment]
Ah.

I haven't tested Blazor Client Side compatibility with my package.

This library uses sync validation to prevent CSS / HTML layout from erroring:

https://github.com/ryanelian/FluentValidation.Blazor/blob/master/FluentValidation.Blazor/FluentValidator.cs#L114-L118

I suspect that because the validation was called synchronously, it exploded when blocking an async operation in client-side Blazor.

Changing THAT to async validation would be easy, but it will break CSS and HTML, which I'm sure not desirable.

I'm honestly not sure what the solution would be here. ASP.NET Blazor should first add support for async validation in Edit Context Hook before async validation could be performed:

https://github.com/ryanelian/FluentValidation.Blazor/blob/master/FluentValidation.Blazor/FluentValidator.cs#L100-L106

If you would like to champion this change, please let Microsoft guys know about this quirk?

**Comment by termon** [comment]
I had noted your comment in the code regarding not using Async in validators, but hoped the issue might be resolved with latest core updates. Thanks for taking a look.

**Comment by ryanelian** [comment]
I just did some spelunking on ASP.NET Core Blazor repo issues.

https://github.com/dotnet/aspnetcore/issues/11914

https://github.com/dotnet/aspnetcore/pull/14818

It's apparently fixed as part as 3.1 (which should already be released?). This library was developed during 3.0.0 so my issue was valid at the time of the writing.

I'll try to do some testing this or next week regarding the issue and release a beta (with FluentValidation 9) addressing this issue if my fix is correct.

**Comment by ryanelian** [comment]
Library now should be compatible with Client-Side Blazor.

New Client-Side Blazor demo projects are added, please check them out:

https://github.com/ryanelian/FluentValidation.Blazor/tree/master/DemoWASM/Client

**Comment by termon** [comment]
@ryanelian Great job - works great. Thanks.
