### ISSUE TITLE
Silent errors misleading

### ISSUE THREAD

**Issue by bdovaz** [ryanelian/FluentValidation.Blazor#42]
I would like to see an option to explicitly check missing validators existence:

https://github.com/ryanelian/FluentValidation.Blazor/blob/master/FluentValidation.Blazor/FluentValidator.cs#L248

I my case I wrongly did this:

RuleFor(e => e.User.Username).NotEmpty();

And I should do this:

RuleFor(e => e.User).SetValidator(userValidator);

If I don't do this it silently fails because there is no "userValidator".

There should be an API to opt to validate this or not.

**Comment by ryanelian** [comment]
I don't know how to solve this with the tools and APIs that Blazor provide, PR welcome.

**Comment by bdovaz** [comment]
> I don't know how to solve this with the tools and APIs that Blazor provide, PR welcome.

@ryanelian I meant instead of just "return;" create a opt-in configuration (default false so it's not a breaking change) that does this:

```csharp
if (options.throwOnValidatorNotFound) {
 // Throw an exception
} else {
 return;
}
```

**Comment by ryanelian** [comment]
See, this is the problem with your proposed solution,

Let's say you have a class:

```cs
public class Something
{
   public Child1 Child1 { set; get; }

   public Child2 Child2 { set; get; }
}
```

If you expect to validate `Child1` and **NOT** validate `Child2`, the library will throw when validating `Child2` because there are no validators for it.
