### ISSUE TITLE
Blazor WASM Project With Both Client & Server Validation

### ISSUE THREAD

**Issue by codemaestro3000** [ryanelian/FluentValidation.Blazor#53]
Hi there!

Just as the title says, I have a project with both Client & Server Fluent validation.  I use the `FluentValidator` for the client side validation. I wanted to take advantage of your `ModelGraphCache` for mapping the server validations to a validator (similar to your `FluentValidator` except manual) on the client side, but it's marked internal. I'm just curious if you had any reservations to opening it up?

**Comment by ryanelian** [comment]
>  I wanted to take advantage of your ModelGraphCache for mapping the server validations to a validator (similar to your FluentValidator except manual) on the client side, but it's marked internal. I'm just curious if you had any reservations to opening it up?

It's an internal API for a reason: I don't want to be held responsible if some day I decided to nuke it out of the project.

It's only one file tho, you can always copy it to your project :)
