### ISSUE TITLE
Is this repo abandoned?

### ISSUE THREAD

**Issue by Fredolx** [ryanelian/FluentValidation.Blazor#81]
Hi maintainers,

PRs to upgrade to FluentValidation 10 are still pending after weeks. Is there a problem with those or is this repo abandoned? I'm not asking to be rude/mean, I prefer this lib over the others for FluentValidation in Blazor, but the potential future lack of support might be a problem if I use this lib in my projects. 

Thank you!

**Comment by geidans** [comment]
Looks like it...

**Comment by nheath99** [comment]
Check out this fork that is keeping the project alive: https://github.com/pablopioli/FluentValidation.Blazor
